#!/bin/bash
set -e

DEBUG=no
STATIC="-static"

CC=${CC:-clang}

if [[ "$1" == debug ]]; then
	DEBUG=yes
	CFLAGS="-O0 -g $CFLAGS"
	if [[ "$2" == undefined ]]; then
		CFLAGS="-fsanitize=undefined $CFLAGS"
	elif [[ "$2" == address ]]; then
		CFLAGS="-fsanitize=address -fsanitize=leak $CFLAGS"
		STATIC=""
	elif [[ "$2" == memory ]]; then
		CFLAGS="-fsanitize=memory $CFLAGS"
	fi
fi

if [[ DEBUG == no ]]; then
	CFLAGS="-O3 $CFLAGS"
fi

CFLAGS="-Wall -Weverything -Wno-gnu-folding-constant -Wno-gnu-empty-initializer -Wno-zero-length-array -Wno-vla -Wno-padded -Wno-logical-op-parentheses -Wno-reserved-id-macro -Wno-missing-prototypes $CFLAGS"

CFLAGS="-std=gnu11 -x c $CFLAGS"

./gen_unicode_tables
$CC $STATIC $CFLAGS -o mepa src/main.c
